### ISSUE TITLE
Problem making request to server using Flask-HTTPAuth

### ISSUE THREAD

**Issue by cmpalmer66** [inorganik/digest-auth-request#11]
I'm making a simple Digest Authentication request to a service written with Flash-HTTPAuth. Basic Authentication works, Digest Authentication directly through the browser works, but when I do a request using this library, I get a self.firstRequest.readyState = 4, but a self.firstRequest.status of 0.

Problem may be with the server, but other methods of calling that service works. Can provide sample code.

**Comment by inorganik** [comment]
Did you turn logging on? Did you get the digest headers back? If so, what were they?

**Comment by inorganik** [comment]
Got no response from @cmpalmer66 for months so closing this
