### ISSUE TITLE
Suppress Browser popup on Challenge

### ISSUE THREAD

**Issue by nuthansantharam** [inorganik/digest-auth-request#14]
How can we disable the default browser up on 401 challenge? Can we handle that purely in JavaScript? I don't want to show the popup to the user.

Thanks,
Nuthan.

**Comment by inorganik** [comment]
This lib handles the authentication and no popups are ever shown - you just need to provide it with username/password. If you're getting a popup you must be trying to access a digest auth protected resource from the browser directly. Before they get to that page, have them enter username/pw however you wish and use that to create your digesetAuthRequest.js object which will handle the requests and return json data.

**Comment by nuthansantharam** [comment]
Thanks for the reply.. The popup disappeared with the latest release. But, How do I handle the browser preflight requests in the lib? Does the lib support CORS? What changes do I need to incorporate in the lib to make this work?

Thanks.

**Comment by inorganik** [comment]
I think I explained it pretty clearly in my previous reply - you need to give the lib a username/pw. So you need to figure out a way to do that before the user tries to hit a protected resource. CORS issues arise because of browser security. So it depends what browser you're using, and if your server is setup to allow CORS requests.

**Comment by inorganik** [comment]
I misunderstood what you meant by "preflight request" - If you just configure your server properly CORS shouldn't be an issue. This lib doesn't do preflight requests - but you shouldn't need them.

**Comment by nuthankumarns** [comment]
Thanks for the reply inorganik, The library authorizes for the digest mechanism, just that, there was additional double quotes being added during parsing of digest headers(www-authenticate). Adding the regex to remove the quotes before the key match fixed it..

```javascript
val = val.replace(/['"]+/g, '');
```

Also, the browser pops-up when the withCredentials to true. Unsetting or not setting it fixes the pop up. Might help for others.

```javascript
xhr.withCredentials = false;//Will not pop-up
xhr.withCredentials = true;//Will pop-up
```

**Comment by inorganik** [comment]
Thanks for those. How were you running into the pop-up, since `withCredentials` is never set anywhere? 

If you want to submit a PR, I can merge, but if you don't I can just add your improvements. Let me know.

**Comment by nuthankumarns** [comment]
Sorry for the delay, I have modified the digest Auth - wrapped as requirejs module. Also, modified to handle the challenges multiple times and also on the verge of including IE's XDomainRequest. I don't think I can submit a PR to existing code, let me know if you want me to send that.

I was performing a CORS request, and thought xhr.withCredentials has to be set to true to make CORS. My bad, its XHR feature.

You can add those improvements.
```javascript  
...
var equalIndex = digestHeaders[i].indexOf('='),
                        key = digestHeaders[i].substring(0, equalIndex),
                        val = digestHeaders[i].substring(equalIndex + 1);
                    val = val.replace(/['"]+/g, '');
...
```
