### ISSUE TITLE
noob needs help

### ISSUE THREAD

**Issue by ehabtanta** [inorganik/digest-auth-request#15]
hi sir 
this is not an issue with the app the issue is with me 

i need to send post request to my router that uses digest-auth and i think your tool is the best to do this 

but i dont know how to run .js files do i need specific application on windows or to run it on centos ?

i have installed java & nodejs in my windows but still when i run the tool in cmd it gives no output

+how to install the dependency i have downloaded it but it is a punch o .js files

i know the address  port  relame  user  and password
i have the form of the post request 

but i need to know how to feed the tool with this info and how to run the tool 

thanks aloot

**Comment by inorganik** [comment]
Hmm, try this link: http://bit.ly/1WrncHe
