### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by oskbor** [inorganik/digest-auth-request#16]
Hi, which browsers does this work in?
I have tried with Chrome and Firefox but I am getting the browser login popup when the browser receives the initial 401.

**Comment by inorganik** [comment]
It should work with any browser - This lib handles the authentication and no popups are ever shown - you just need to provide it with username/password. If you're getting a popup you must be trying to access a digest auth protected resource from the browser directly. Before the user gets to that page, have them enter username/pw however you wish and use that to create your digesetAuthRequest.js object which will handle the requests and return json data.
