### ISSUE TITLE
Update version on npm

### ISSUE THREAD

**Issue by pezfish** [inorganik/digest-auth-request#29]
It looks like the version that's posted on npm is not up to date with the version that's in this repo.

When doing an install I'm getting the version from this commit: https://github.com/inorganik/digest-auth-request/commit/6b522e07fcf0c5c7c4c07117c77b49384080e606, which is a couple commits behind this repo.

**Comment by inorganik** [comment]
Thanks, I bumped it to 0.7.0 and published on npm.
